spring:
  datasource:
    url: jdbc:h2:mem:movies
    username: admin
    password: password
  h2:
    console:
      enabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html

jwt:
  secret: 9e37298f54dbddab553b69e9fa6cf0b1c5961c016c4d6a03f28f51e49f31685a
  issuer: movies
  tokenValidityInMinutes: 5
