export enum Genre {
  ACTION = "Action",
  ADVENTURE = "Adventure",
  ANIMATION = "Animation",
  COMEDY = "Comedy",
  CRIME = "Crime",
  DOCUMENTARY = "Documentary",
  DRAMA = "Drama",
  FAMILY = "Family",
  FANTASY = "Fantasy",
  HISTORY = "History",
  HORROR = "Horror",
  MUSIC = "Music",
  MISTERY = "Mystery",
  ROMANCE = "Romance",
  SCIENCE_FICTION = "Science Fiction",
  TV_MOVIE = "TV Movie",
  THRILLER = "Thriller",
  WAR = "War",
  WESTERN = "Western",
};
